const promisefour = new Promise(function(resolve,reject){
//     setTimeout(()=>{
//         let error = false;
//         if(!error){
//             let userobj = {
//                 name: "Ks",
//                 age: 20
//             };
//             resolve(userobj);
//         }else{
//             reject("ERROR");
//         }

//     },1000);
// });

// promisefour
// .then(function(user){
//     console.log(user);
//     return user.name;
// })
// .then((usernm)=>{
//     console.log(usernm);
// })
// .catch((msg) =>{
//     console.log(msg);
// })
// .finally(() => console.log("Finally this is over"));
